// <auto-generated />
namespace ClassifiedApp.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ClassifiedsV5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClassifiedsV5));
        
        string IMigrationMetadata.Id
        {
            get { return "201511141914298_Classifieds-V5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
