//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassifiedApp.BusinessServices.SyriatelWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SyriatelWebService.APISoap")]
    public interface APISoap {
        
        // CODEGEN: Generating message contract since element name logingName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterNewUserSCS", ReplyAction="*")]
        ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSResponse RegisterNewUserSCS(ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterNewUserSCS", ReplyAction="*")]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSResponse> RegisterNewUserSCSAsync(ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSRequest request);
        
        // CODEGEN: Generating message contract since element name scsWebSiteUser from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCS_SendSMS", ReplyAction="*")]
        ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSResponse SCS_SendSMS(ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCS_SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSResponse> SCS_SendSMSAsync(ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name admin_user_name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Normal_By_Admin", ReplyAction="*")]
        ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminResponse Add_Normal_By_Admin(ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Normal_By_Admin", ReplyAction="*")]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminResponse> Add_Normal_By_AdminAsync(ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminRequest request);
        
        // CODEGEN: Generating message contract since element name agent_user_name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Admin_By_Agent", ReplyAction="*")]
        ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentResponse Add_Admin_By_Agent(ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Admin_By_Agent", ReplyAction="*")]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentResponse> Add_Admin_By_AgentAsync(ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentRequest request);
        
        // CODEGEN: Generating message contract since element name creator_user_name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddContract", ReplyAction="*")]
        ClassifiedApp.BusinessServices.SyriatelWebService.AddContractResponse AddContract(ClassifiedApp.BusinessServices.SyriatelWebService.AddContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddContract", ReplyAction="*")]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.AddContractResponse> AddContractAsync(ClassifiedApp.BusinessServices.SyriatelWebService.AddContractRequest request);
        
        // CODEGEN: Generating message contract since element name job_name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendBroadcastSMS", ReplyAction="*")]
        ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSResponse SendBroadcastSMS(ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendBroadcastSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSResponse> SendBroadcastSMSAsync(ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSRequest request);
        
        // CODEGEN: Generating message contract since element name job_name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSResponse SendSMS(ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSResponse> SendSMSAsync(ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name user_name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckJobStatus", ReplyAction="*")]
        ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusResponse CheckJobStatus(ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckJobStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusResponse> CheckJobStatusAsync(ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusRequest request);
        
        // CODEGEN: Generating message contract since element name user_name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserStatus", ReplyAction="*")]
        ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusResponse CheckUserStatus(ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusResponse> CheckUserStatusAsync(ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterNewUserSCSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterNewUserSCS", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSRequestBody Body;
        
        public RegisterNewUserSCSRequest() {
        }
        
        public RegisterNewUserSCSRequest(ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterNewUserSCSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string logingName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long user_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobileNumber;
        
        public RegisterNewUserSCSRequestBody() {
        }
        
        public RegisterNewUserSCSRequestBody(string logingName, string loginPass, long user_id, string mobileNumber) {
            this.logingName = logingName;
            this.loginPass = loginPass;
            this.user_id = user_id;
            this.mobileNumber = mobileNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterNewUserSCSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterNewUserSCSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSResponseBody Body;
        
        public RegisterNewUserSCSResponse() {
        }
        
        public RegisterNewUserSCSResponse(ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterNewUserSCSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterNewUserSCSResult;
        
        public RegisterNewUserSCSResponseBody() {
        }
        
        public RegisterNewUserSCSResponseBody(string RegisterNewUserSCSResult) {
            this.RegisterNewUserSCSResult = RegisterNewUserSCSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SCS_SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SCS_SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSRequestBody Body;
        
        public SCS_SendSMSRequest() {
        }
        
        public SCS_SendSMSRequest(ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SCS_SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string scsWebSiteUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string scsWebSitePass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long user_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string secretCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string to;
        
        public SCS_SendSMSRequestBody() {
        }
        
        public SCS_SendSMSRequestBody(string scsWebSiteUser, string scsWebSitePass, long user_id, string secretCode, string msg, string to) {
            this.scsWebSiteUser = scsWebSiteUser;
            this.scsWebSitePass = scsWebSitePass;
            this.user_id = user_id;
            this.secretCode = secretCode;
            this.msg = msg;
            this.to = to;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SCS_SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SCS_SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSResponseBody Body;
        
        public SCS_SendSMSResponse() {
        }
        
        public SCS_SendSMSResponse(ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SCS_SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SCS_SendSMSResult;
        
        public SCS_SendSMSResponseBody() {
        }
        
        public SCS_SendSMSResponseBody(string SCS_SendSMSResult) {
            this.SCS_SendSMSResult = SCS_SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_Normal_By_AdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_Normal_By_Admin", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminRequestBody Body;
        
        public Add_Normal_By_AdminRequest() {
        }
        
        public Add_Normal_By_AdminRequest(ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_Normal_By_AdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string admin_user_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string admin_pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string first_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string last_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string user_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string optionals;
        
        public Add_Normal_By_AdminRequestBody() {
        }
        
        public Add_Normal_By_AdminRequestBody(string admin_user_name, string admin_pass, string first_name, string last_name, string user_name, string mobile, string optionals) {
            this.admin_user_name = admin_user_name;
            this.admin_pass = admin_pass;
            this.first_name = first_name;
            this.last_name = last_name;
            this.user_name = user_name;
            this.mobile = mobile;
            this.optionals = optionals;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_Normal_By_AdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_Normal_By_AdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminResponseBody Body;
        
        public Add_Normal_By_AdminResponse() {
        }
        
        public Add_Normal_By_AdminResponse(ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_Normal_By_AdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Add_Normal_By_AdminResult;
        
        public Add_Normal_By_AdminResponseBody() {
        }
        
        public Add_Normal_By_AdminResponseBody(string Add_Normal_By_AdminResult) {
            this.Add_Normal_By_AdminResult = Add_Normal_By_AdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_Admin_By_AgentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_Admin_By_Agent", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentRequestBody Body;
        
        public Add_Admin_By_AgentRequest() {
        }
        
        public Add_Admin_By_AgentRequest(ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_Admin_By_AgentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string agent_user_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string agent_pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string first_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string last_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string user_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string optionals;
        
        public Add_Admin_By_AgentRequestBody() {
        }
        
        public Add_Admin_By_AgentRequestBody(string agent_user_name, string agent_pass, string first_name, string last_name, string user_name, string password, string optionals) {
            this.agent_user_name = agent_user_name;
            this.agent_pass = agent_pass;
            this.first_name = first_name;
            this.last_name = last_name;
            this.user_name = user_name;
            this.password = password;
            this.optionals = optionals;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_Admin_By_AgentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_Admin_By_AgentResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentResponseBody Body;
        
        public Add_Admin_By_AgentResponse() {
        }
        
        public Add_Admin_By_AgentResponse(ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_Admin_By_AgentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Add_Admin_By_AgentResult;
        
        public Add_Admin_By_AgentResponseBody() {
        }
        
        public Add_Admin_By_AgentResponseBody(string Add_Admin_By_AgentResult) {
            this.Add_Admin_By_AgentResult = Add_Admin_By_AgentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddContract", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.AddContractRequestBody Body;
        
        public AddContractRequest() {
        }
        
        public AddContractRequest(ClassifiedApp.BusinessServices.SyriatelWebService.AddContractRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddContractRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string creator_user_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string creator_pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int contract_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int message_count;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string expire_date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string optionals;
        
        public AddContractRequestBody() {
        }
        
        public AddContractRequestBody(string creator_user_name, string creator_pass, string user_name, int contract_type, int message_count, string expire_date, string optionals) {
            this.creator_user_name = creator_user_name;
            this.creator_pass = creator_pass;
            this.user_name = user_name;
            this.contract_type = contract_type;
            this.message_count = message_count;
            this.expire_date = expire_date;
            this.optionals = optionals;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddContractResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.AddContractResponseBody Body;
        
        public AddContractResponse() {
        }
        
        public AddContractResponse(ClassifiedApp.BusinessServices.SyriatelWebService.AddContractResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddContractResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddContractResult;
        
        public AddContractResponseBody() {
        }
        
        public AddContractResponseBody(string AddContractResult) {
            this.AddContractResult = AddContractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBroadcastSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBroadcastSMS", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSRequestBody Body;
        
        public SendBroadcastSMSRequest() {
        }
        
        public SendBroadcastSMSRequest(ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendBroadcastSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string job_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string scheduled_date;
        
        public SendBroadcastSMSRequestBody() {
        }
        
        public SendBroadcastSMSRequestBody(string job_name, string user_name, string password, string msg, string sender, string to, string scheduled_date) {
            this.job_name = job_name;
            this.user_name = user_name;
            this.password = password;
            this.msg = msg;
            this.sender = sender;
            this.to = to;
            this.scheduled_date = scheduled_date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBroadcastSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBroadcastSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSResponseBody Body;
        
        public SendBroadcastSMSResponse() {
        }
        
        public SendBroadcastSMSResponse(ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendBroadcastSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendBroadcastSMSResult;
        
        public SendBroadcastSMSResponseBody() {
        }
        
        public SendBroadcastSMSResponseBody(string SendBroadcastSMSResult) {
            this.SendBroadcastSMSResult = SendBroadcastSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string job_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string scheduled_date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string repeating;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string repeat_until;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(string job_name, string user_name, string password, string msg, string sender, string to, string scheduled_date, string repeating, string repeat_until) {
            this.job_name = job_name;
            this.user_name = user_name;
            this.password = password;
            this.msg = msg;
            this.sender = sender;
            this.to = to;
            this.scheduled_date = scheduled_date;
            this.repeating = repeating;
            this.repeat_until = repeat_until;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(string SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckJobStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckJobStatus", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusRequestBody Body;
        
        public CheckJobStatusRequest() {
        }
        
        public CheckJobStatusRequest(ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckJobStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int job_id;
        
        public CheckJobStatusRequestBody() {
        }
        
        public CheckJobStatusRequestBody(string user_name, string password, int job_id) {
            this.user_name = user_name;
            this.password = password;
            this.job_id = job_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckJobStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckJobStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusResponseBody Body;
        
        public CheckJobStatusResponse() {
        }
        
        public CheckJobStatusResponse(ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckJobStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckJobStatusResult;
        
        public CheckJobStatusResponseBody() {
        }
        
        public CheckJobStatusResponseBody(string CheckJobStatusResult) {
            this.CheckJobStatusResult = CheckJobStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserStatus", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusRequestBody Body;
        
        public CheckUserStatusRequest() {
        }
        
        public CheckUserStatusRequest(ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string target_user_name;
        
        public CheckUserStatusRequestBody() {
        }
        
        public CheckUserStatusRequestBody(string user_name, string password, string target_user_name) {
            this.user_name = user_name;
            this.password = password;
            this.target_user_name = target_user_name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusResponseBody Body;
        
        public CheckUserStatusResponse() {
        }
        
        public CheckUserStatusResponse(ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckUserStatusResult;
        
        public CheckUserStatusResponseBody() {
        }
        
        public CheckUserStatusResponseBody(string CheckUserStatusResult) {
            this.CheckUserStatusResult = CheckUserStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APISoapChannel : ClassifiedApp.BusinessServices.SyriatelWebService.APISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APISoapClient : System.ServiceModel.ClientBase<ClassifiedApp.BusinessServices.SyriatelWebService.APISoap>, ClassifiedApp.BusinessServices.SyriatelWebService.APISoap {
        
        public APISoapClient() {
        }
        
        public APISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSResponse ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.RegisterNewUserSCS(ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSRequest request) {
            return base.Channel.RegisterNewUserSCS(request);
        }
        
        public string RegisterNewUserSCS(string logingName, string loginPass, long user_id, string mobileNumber) {
            ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSRequestBody();
            inValue.Body.logingName = logingName;
            inValue.Body.loginPass = loginPass;
            inValue.Body.user_id = user_id;
            inValue.Body.mobileNumber = mobileNumber;
            ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSResponse retVal = ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).RegisterNewUserSCS(inValue);
            return retVal.Body.RegisterNewUserSCSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSResponse> ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.RegisterNewUserSCSAsync(ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSRequest request) {
            return base.Channel.RegisterNewUserSCSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSResponse> RegisterNewUserSCSAsync(string logingName, string loginPass, long user_id, string mobileNumber) {
            ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.RegisterNewUserSCSRequestBody();
            inValue.Body.logingName = logingName;
            inValue.Body.loginPass = loginPass;
            inValue.Body.user_id = user_id;
            inValue.Body.mobileNumber = mobileNumber;
            return ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).RegisterNewUserSCSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSResponse ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.SCS_SendSMS(ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSRequest request) {
            return base.Channel.SCS_SendSMS(request);
        }
        
        public string SCS_SendSMS(string scsWebSiteUser, string scsWebSitePass, long user_id, string secretCode, string msg, string to) {
            ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSRequestBody();
            inValue.Body.scsWebSiteUser = scsWebSiteUser;
            inValue.Body.scsWebSitePass = scsWebSitePass;
            inValue.Body.user_id = user_id;
            inValue.Body.secretCode = secretCode;
            inValue.Body.msg = msg;
            inValue.Body.to = to;
            ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSResponse retVal = ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).SCS_SendSMS(inValue);
            return retVal.Body.SCS_SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSResponse> ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.SCS_SendSMSAsync(ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSRequest request) {
            return base.Channel.SCS_SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSResponse> SCS_SendSMSAsync(string scsWebSiteUser, string scsWebSitePass, long user_id, string secretCode, string msg, string to) {
            ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.SCS_SendSMSRequestBody();
            inValue.Body.scsWebSiteUser = scsWebSiteUser;
            inValue.Body.scsWebSitePass = scsWebSitePass;
            inValue.Body.user_id = user_id;
            inValue.Body.secretCode = secretCode;
            inValue.Body.msg = msg;
            inValue.Body.to = to;
            return ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).SCS_SendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminResponse ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.Add_Normal_By_Admin(ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminRequest request) {
            return base.Channel.Add_Normal_By_Admin(request);
        }
        
        public string Add_Normal_By_Admin(string admin_user_name, string admin_pass, string first_name, string last_name, string user_name, string mobile, string optionals) {
            ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminRequestBody();
            inValue.Body.admin_user_name = admin_user_name;
            inValue.Body.admin_pass = admin_pass;
            inValue.Body.first_name = first_name;
            inValue.Body.last_name = last_name;
            inValue.Body.user_name = user_name;
            inValue.Body.mobile = mobile;
            inValue.Body.optionals = optionals;
            ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminResponse retVal = ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).Add_Normal_By_Admin(inValue);
            return retVal.Body.Add_Normal_By_AdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminResponse> ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.Add_Normal_By_AdminAsync(ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminRequest request) {
            return base.Channel.Add_Normal_By_AdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminResponse> Add_Normal_By_AdminAsync(string admin_user_name, string admin_pass, string first_name, string last_name, string user_name, string mobile, string optionals) {
            ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.Add_Normal_By_AdminRequestBody();
            inValue.Body.admin_user_name = admin_user_name;
            inValue.Body.admin_pass = admin_pass;
            inValue.Body.first_name = first_name;
            inValue.Body.last_name = last_name;
            inValue.Body.user_name = user_name;
            inValue.Body.mobile = mobile;
            inValue.Body.optionals = optionals;
            return ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).Add_Normal_By_AdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentResponse ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.Add_Admin_By_Agent(ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentRequest request) {
            return base.Channel.Add_Admin_By_Agent(request);
        }
        
        public string Add_Admin_By_Agent(string agent_user_name, string agent_pass, string first_name, string last_name, string user_name, string password, string optionals) {
            ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentRequestBody();
            inValue.Body.agent_user_name = agent_user_name;
            inValue.Body.agent_pass = agent_pass;
            inValue.Body.first_name = first_name;
            inValue.Body.last_name = last_name;
            inValue.Body.user_name = user_name;
            inValue.Body.password = password;
            inValue.Body.optionals = optionals;
            ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentResponse retVal = ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).Add_Admin_By_Agent(inValue);
            return retVal.Body.Add_Admin_By_AgentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentResponse> ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.Add_Admin_By_AgentAsync(ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentRequest request) {
            return base.Channel.Add_Admin_By_AgentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentResponse> Add_Admin_By_AgentAsync(string agent_user_name, string agent_pass, string first_name, string last_name, string user_name, string password, string optionals) {
            ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.Add_Admin_By_AgentRequestBody();
            inValue.Body.agent_user_name = agent_user_name;
            inValue.Body.agent_pass = agent_pass;
            inValue.Body.first_name = first_name;
            inValue.Body.last_name = last_name;
            inValue.Body.user_name = user_name;
            inValue.Body.password = password;
            inValue.Body.optionals = optionals;
            return ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).Add_Admin_By_AgentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClassifiedApp.BusinessServices.SyriatelWebService.AddContractResponse ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.AddContract(ClassifiedApp.BusinessServices.SyriatelWebService.AddContractRequest request) {
            return base.Channel.AddContract(request);
        }
        
        public string AddContract(string creator_user_name, string creator_pass, string user_name, int contract_type, int message_count, string expire_date, string optionals) {
            ClassifiedApp.BusinessServices.SyriatelWebService.AddContractRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.AddContractRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.AddContractRequestBody();
            inValue.Body.creator_user_name = creator_user_name;
            inValue.Body.creator_pass = creator_pass;
            inValue.Body.user_name = user_name;
            inValue.Body.contract_type = contract_type;
            inValue.Body.message_count = message_count;
            inValue.Body.expire_date = expire_date;
            inValue.Body.optionals = optionals;
            ClassifiedApp.BusinessServices.SyriatelWebService.AddContractResponse retVal = ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).AddContract(inValue);
            return retVal.Body.AddContractResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.AddContractResponse> ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.AddContractAsync(ClassifiedApp.BusinessServices.SyriatelWebService.AddContractRequest request) {
            return base.Channel.AddContractAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.AddContractResponse> AddContractAsync(string creator_user_name, string creator_pass, string user_name, int contract_type, int message_count, string expire_date, string optionals) {
            ClassifiedApp.BusinessServices.SyriatelWebService.AddContractRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.AddContractRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.AddContractRequestBody();
            inValue.Body.creator_user_name = creator_user_name;
            inValue.Body.creator_pass = creator_pass;
            inValue.Body.user_name = user_name;
            inValue.Body.contract_type = contract_type;
            inValue.Body.message_count = message_count;
            inValue.Body.expire_date = expire_date;
            inValue.Body.optionals = optionals;
            return ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).AddContractAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSResponse ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.SendBroadcastSMS(ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSRequest request) {
            return base.Channel.SendBroadcastSMS(request);
        }
        
        public string SendBroadcastSMS(string job_name, string user_name, string password, string msg, string sender, string to, string scheduled_date) {
            ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSRequestBody();
            inValue.Body.job_name = job_name;
            inValue.Body.user_name = user_name;
            inValue.Body.password = password;
            inValue.Body.msg = msg;
            inValue.Body.sender = sender;
            inValue.Body.to = to;
            inValue.Body.scheduled_date = scheduled_date;
            ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSResponse retVal = ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).SendBroadcastSMS(inValue);
            return retVal.Body.SendBroadcastSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSResponse> ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.SendBroadcastSMSAsync(ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSRequest request) {
            return base.Channel.SendBroadcastSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSResponse> SendBroadcastSMSAsync(string job_name, string user_name, string password, string msg, string sender, string to, string scheduled_date) {
            ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.SendBroadcastSMSRequestBody();
            inValue.Body.job_name = job_name;
            inValue.Body.user_name = user_name;
            inValue.Body.password = password;
            inValue.Body.msg = msg;
            inValue.Body.sender = sender;
            inValue.Body.to = to;
            inValue.Body.scheduled_date = scheduled_date;
            return ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).SendBroadcastSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSResponse ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.SendSMS(ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public string SendSMS(string job_name, string user_name, string password, string msg, string sender, string to, string scheduled_date, string repeating, string repeat_until) {
            ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSRequestBody();
            inValue.Body.job_name = job_name;
            inValue.Body.user_name = user_name;
            inValue.Body.password = password;
            inValue.Body.msg = msg;
            inValue.Body.sender = sender;
            inValue.Body.to = to;
            inValue.Body.scheduled_date = scheduled_date;
            inValue.Body.repeating = repeating;
            inValue.Body.repeat_until = repeat_until;
            ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSResponse retVal = ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSResponse> ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.SendSMSAsync(ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSResponse> SendSMSAsync(string job_name, string user_name, string password, string msg, string sender, string to, string scheduled_date, string repeating, string repeat_until) {
            ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.SendSMSRequestBody();
            inValue.Body.job_name = job_name;
            inValue.Body.user_name = user_name;
            inValue.Body.password = password;
            inValue.Body.msg = msg;
            inValue.Body.sender = sender;
            inValue.Body.to = to;
            inValue.Body.scheduled_date = scheduled_date;
            inValue.Body.repeating = repeating;
            inValue.Body.repeat_until = repeat_until;
            return ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).SendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusResponse ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.CheckJobStatus(ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusRequest request) {
            return base.Channel.CheckJobStatus(request);
        }
        
        public string CheckJobStatus(string user_name, string password, int job_id) {
            ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusRequestBody();
            inValue.Body.user_name = user_name;
            inValue.Body.password = password;
            inValue.Body.job_id = job_id;
            ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusResponse retVal = ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).CheckJobStatus(inValue);
            return retVal.Body.CheckJobStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusResponse> ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.CheckJobStatusAsync(ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusRequest request) {
            return base.Channel.CheckJobStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusResponse> CheckJobStatusAsync(string user_name, string password, int job_id) {
            ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.CheckJobStatusRequestBody();
            inValue.Body.user_name = user_name;
            inValue.Body.password = password;
            inValue.Body.job_id = job_id;
            return ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).CheckJobStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusResponse ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.CheckUserStatus(ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusRequest request) {
            return base.Channel.CheckUserStatus(request);
        }
        
        public string CheckUserStatus(string user_name, string password, string target_user_name) {
            ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusRequestBody();
            inValue.Body.user_name = user_name;
            inValue.Body.password = password;
            inValue.Body.target_user_name = target_user_name;
            ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusResponse retVal = ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).CheckUserStatus(inValue);
            return retVal.Body.CheckUserStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusResponse> ClassifiedApp.BusinessServices.SyriatelWebService.APISoap.CheckUserStatusAsync(ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusRequest request) {
            return base.Channel.CheckUserStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusResponse> CheckUserStatusAsync(string user_name, string password, string target_user_name) {
            ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusRequest inValue = new ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusRequest();
            inValue.Body = new ClassifiedApp.BusinessServices.SyriatelWebService.CheckUserStatusRequestBody();
            inValue.Body.user_name = user_name;
            inValue.Body.password = password;
            inValue.Body.target_user_name = target_user_name;
            return ((ClassifiedApp.BusinessServices.SyriatelWebService.APISoap)(this)).CheckUserStatusAsync(inValue);
        }
    }
}
